In [2]:
import math as m
import numpy as np
import matplotlib.pyplot as plt

Data set

In [3]:
A=np.array([[0, 10, 5, 2], [10, 0, 7, 3], [5, 7, 0, 6], [2, 3, 6, 0]])
n=4
C_0=100
C_t=1
maxval=A.max()

Objective function: $k \cdot C_0 + C_t \cdot TS$

In [4]:
x=np.array([0,1,1,1])
k=3

2 part. Divide all vertices to clusters

In [5]:
cl=np.arange(0,n)
dist=(np.zeros(n)+maxval)*((x-1)*(-1))
print(dist)
for i in range(n):
    if x[i]==0:
        for j in range(n):
            if A[i,j]>0 and x[j]==1 and dist[i]>A[i,j]:
                dist[i]=A[i,j]
                cl[i]=j
    
print(dist)
print(cl)

[ 10.   0.   0.   0.]
[ 2.  0.  0.  0.]
[3 1 2 3]


3 part. Compute TS for this clusters

In [6]:
TS=0
for i in range(n):
    if x[i]==0:
        TS=TS+2*dist[i]
print(TS)
TotCost=k*C_0+C_t*TS
print(TotCost)

4.0
304.0


Heuristic algorithm with bad choosing of depots and bad TS

In [11]:
A=np.array([[0, 10, 5, 2], [10, 0, 7, 3], [5, 7, 0, 6], [2, 3, 6, 0]])
n=4
C_0=100
C_t=1
maxval=A.max()
x=np.array([1,1,1,1])
Cost=np.zeros(n)+n*C_0
k=n
e=np.zeros(n)+1
while k > 1:
    m=0
    x1=np.copy(x)
    while m < n:
        if x[m]==0:
            m=m+1
        else:
            x[m]=0
            
            cl=np.arange(0,n)
            dist=(np.zeros(n)+maxval)*((x-1)*(-1))
            print(dist)
            for i in range(n):
                if x[i]==0:
                    for j in range(n):
                        if A[i,j]>0 and x[j]==1 and dist[i]>A[i,j]:
                            dist[i]=A[i,j]
                            cl[i]=j
            print(dist)
            print(cl)
            TS=0
            for i in range(n):
                if x[i]==0:
                    TS=TS+2*dist[i]
            print(TS)
            TotCost=(k-1)*C_0+C_t*TS
            print(TotCost)
            if TotCost<Cost[k-1]:
                Cost[k-2]=TotCost
                k=k-1
                m=n
            else:
                x[m]=1
                m+=1
                
    if e.dot(x1-x)==0:
        k1=np.copy(k)
        k=0

[ 10.   0.   0.   0.]
[ 2.  0.  0.  0.]
[3 1 2 3]
4.0
304.0
[ 10.  10.   0.   0.]
[ 2.  3.  0.  0.]
[3 3 2 3]
10.0
210.0
[ 10.  10.  10.   0.]
[ 2.  3.  6.  0.]
[3 3 3 3]
22.0
122.0
